### ISSUE TITLE
Unable to make outbound RESTful API calls after upgrade from Madrid to New York

### ISSUE THREAD

**Issue by michaelford85** [ansible/product-demos#1]
I have a ServiceNow developer instance which at one time week was running the Madrid release. Using the ServiceNow documentation showing Google as an Oauth2 provider, I set up ServiceNow to successfully make outbound RESTful calls into Ansible Tower. I used a self-signed certificate from Ansible Tower in order to make these calls. 

When available, I upgraded my developer instance to New York. Where I was able to make outbound RESTful calls before, I am now unable to. Inspection into the Logs shows that ServiceNow is not seeing certificate for the web server:

![image](https://user-images.githubusercontent.com/17229266/75701143-dce44600-5c78-11ea-8f98-988ff3001837.png)

I've gone through the settings and everything looks correct. Furthermore, I changed the system properties to ignore any certificate chain and to trust all certificates (just to take those checks out of the equation):

com.glide.communications.httpclient.verify_hostname: false

com.glide.communications.trustmanager_trust_all: true

I am still getting the message "no issuer certificate found for [webserver]." In order to test whether or not this is an issue with self-signed certificates, I created a certificate via letsencrypt.org and installed it to my webserver. This new certificate is not being recognized either, and I am still seeing "no issuer certificate found for [webserver]." This is the case both for Oauth2 authentication as well as basic authentication.

I am at a point where nothing is readily apparent as to something being misconfigured in ServiceNow - does anyone have an idea as to what may have changed from Madrid to New York (and now Orlando) to result in this behavior?

**Comment by SmashDoggo** [comment]
Please try to put the properties com.glide.communications.httpclient.verify_revoked_certificate to false. Create the property if you do not have it already.
This has worked for me.

**Comment by IPvSean** [comment]
Thank you for open an issue.  We have significantly changed the layout of github.com/ansible/product-demos and I think this is no longer an issue.  Please re-open this issue after rebasing your fork and ensuring this is still an issue:

```
git remote add upstream https://github.com/ansible/product-demos.git
git pull --rebase upstream main
```

Sorry for the delay, we realize this repo has not been maintained well in some time and we are working to fix that.
