### ISSUE TITLE
The conditional check 'azure_demo == True' failed. The error was: error while evaluating conditional (azure_demo == True): 'azure_demo' is undefined

### ISSUE THREAD

**Issue by Spredzy** [ansible/product-demos#12]
The `The conditional check 'azure_demo == True' failed. The error was: error while evaluating conditional (azure_demo == True): 'azure_demo' is undefined` can is raised when running ansible workshops on `devel`

**Comment by davidrojas25** [comment]
@Spredzy Can you post your choose_demo.yml file you used here?

**Comment by Spredzy** [comment]
This was an issue I was seeing on the CI of a distinct project that doesn't seem to be an issue anymore. Will re open if I see it again. Sorry for the noise.

**Comment by davidrojas25** [comment]
No problem. I'm going to add common cause here just in case others run into something similar. 'azure_demo' is undefined can occur if you are using an older version of the choose_demo.yml file as your extra vars file. In previous versions that variable didn't exist. By using the latest file it will define is at azure_demo == False, and therefor not give you the error you received. Additionally, if you want to use the new Azure demos you can set it to True and fill in the info below that. An example of how to do that can be found in the example file of choose_demo_example_azure.yml
