### ISSUE TITLE
Expanded Use-Case Request OpenSCAP

### ISSUE THREAD

**Issue by adworjan** [ansible/product-demos#14]
It would be helpful, to include Windows in the OpenSCAP demo as well in order to tell the story of having a single automation tool that can run compliance across the entire architecture. Are there any plans/efforts into this?

**Comment by cloin** [comment]
No current plans around a OpenSCAP for Windows demo. Is OpenSCAP supported by anybody in Windows environments? I haven’t heard of OpenSCAP outside of RHEL.

**Comment by adworjan** [comment]
According to the OpenSCAP site, OpenSCAP is available on various Linux distributions, including Red Hat Enterprise Linux, Fedora and Ubuntu. Since version 1.3.0 OpenSCAP supports also Microsoft Windows.

https://www.open-scap.org/tools/openscap-base/

**Comment by cloin** [comment]
Ah yeah. Nice. Honestly, it has never come up in windows conversations that I’ve had or heard from others so I’d be looking to the field to understand how popular OpenSCAP is in windows environments. It sounds like it might be a difficult narrative to push if it’s not already top of mind and there isn’t a major vendor supporting OpenSCAP on windows.

**Comment by adworjan** [comment]
I'd say it isn't that OpenSCAP is brought up, but the idea of being able to run compliance scans from Ansible easily across both environments. OpenSCAP is the only tool I've been able to find that might provide that capability. This comes up a lot from Linux initial customers that are looking to expand into Windows and have the same concerns around compliance.

**Comment by cloin** [comment]
Good to know. I can look into it.

**Comment by IPvSean** [comment]
Thank you for open an issue.  We have significantly changed the layout of github.com/ansible/product-demos and I think this is no longer an issue.  Please re-open this issue after rebasing your fork and ensuring this is still an issue:

```
git remote add upstream https://github.com/ansible/product-demos.git
git pull --rebase upstream main
```

Sorry for the delay, we realize this repo has not been maintained well in some time and we are working to fix that.
