### ISSUE TITLE
Document injector formatting requirement

### ISSUE THREAD

**Issue by jce-redhat** [ansible/product-demos#142]
when defining injectors for controller credential types (see [linux/setup.yml](https://github.com/ansible/product-demos/blob/9cd49892c66c23e7a60202d2564bf922a1d0ee2b/linux/setup.yml#L26) example), the infra.controller_configuration.credential_types role has an odd requirement for adding two spaces between jinja brackets in order to pass the bracketed variable through to the credential configuration.  see https://github.com/redhat-cop/controller_configuration/tree/devel/roles/credential_types#formating-injectors for details.  this caused some confusion for users of this repo who weren't familiar with the requirement, so a comment should be added for clarity where used.

additionally, the `{% raw %} {% endraw %}` construct is not required when using the infra.controller_configuration.credential_types role and its two space construct.

**Comment by taruch** [comment]
jce/injector merge closes this issue.
