### ISSUE TITLE
VPC report bucket name isn't unique enough

### ISSUE THREAD

**Issue by jce-redhat** [ansible/product-demos#148]
we're leveraging playbooks and roles from the [aws.infrastructure_config_demos repo](https://github.com/ansible-content-lab/aws.infrastructure_config_demos) for a number of the cloud-related demos.  one job template creates a VPC report and writes it to a bucket, but that [bucket name](https://github.com/ansible-content-lab/aws.infrastructure_config_demos/blob/e5f32f8451e7a711f369f2703c10561082f8fec0/roles/reports/defaults/main.yml#L3) isn't unique enough to guarantee that it doesn't already exist globally.  i've created two demo environments today where the bucket already exists, and the VPC report job template fails because it doesn't have write access to the bucket.

a generalized way of approaching this would be to generate a random deployment ID for each product-demos deployment, then use that ID as part of the bucket name.  the ID could be used in future tasks where some unique identifier is required.

**Comment by willtome** [comment]
+1 I noticed this error as well.
