### ISSUE TITLE
Workshop documentation references wrong path

### ISSUE THREAD

**Issue by xtophd** [ansible/product-demos#4]
Navigate to playbooks/03_hardening.yml

Should probably be:

/playbooks/security/hardening.yml

**Comment by IPvSean** [comment]
Thank you for open an issue.  We have significantly changed the layout of github.com/ansible/product-demos and I think this is no longer an issue.  Please re-open this issue after rebasing your fork and ensuring this is still an issue:

```
git remote add upstream https://github.com/ansible/product-demos.git
git pull --rebase upstream main
```

Sorry for the delay, we realize this repo has not been maintained well in some time and we are working to fix that.
