### ISSUE TITLE
SETUP with Demo Category: Cloud fails

### ISSUE THREAD

**Issue by daleroux** [ansible/product-demos#86]
At the very start of the workshop/lab, when running the SETUP Job template with Demo Category:  'Cloud' , the following error pops up: failed: [localhost] (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': 'j760450173010.1206', 'results_file': '/tmp/.ansible_async/j760450173010.1206', 'changed': False, '__workflow_loop_node_item': {'identifier': 'Deploy Windows Blueprint', 'unified_job_template': 'Cloud / AWS / Create VM', 'extra_data': {'vm_name': 'aws_win', 'vm_blueprint': 'windows_full', 'vm_owner': '{{ aws_owner_tag }}'}, 'success_nodes': ['Update Inventory'], 'failure_nodes': ['Ticket - Instance Failed']}, 'ansible_loop_var': '__workflow_loop_node_item'}) => {"__workflows_node_async_results_item": {"__workflow_loop_node_item": {"extra_data": {"vm_blueprint": "windows_full", "vm_name": "aws_win", "vm_owner": "{{ aws_owner_tag }}"}, "failure_nodes": ["Ticket - Instance Failed"], "identifier": "Deploy Windows Blueprint", "success_nodes": ["Update Inventory"], "unified_job_template": "Cloud / AWS / Create VM"}, "ansible_job_id": "j760450173010.1206", "ansible_loop_var": "__workflow_loop_node_item", "changed": false, …

**Comment by willtome** [comment]
Thanks for reporting this issue @daleroux. I don’t have enough information from the error you shared to determine the reason for failure. Can you add the full job log?

You can also review the instructions here (https://github.com/RedHatGov/ansible-tower-samples) to ensure you’ve met all the prerequisites.

**Comment by daleroux** [comment]
Hi Will, 

I followed the instructions above, please see the attachment for the full job log. -Dan
[job_3.txt](https://github.com/ansible/product-demos/files/12396536/job_3.txt)

**Comment by willtome** [comment]
@daleroux I'm going to go ahead and close out this issue. If this is still causing problems please reopen. Thanks!
